# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1376615915);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1376616035);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1376669676);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1376658995);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.slowStartup.averageTime", 1041);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20130806211916");
user_pref("browser.startup.homepage_override.mstone", "23.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1376635650906");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1376635651857");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1376722051857");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1376543400800");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1376549233374");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1376456192896");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 699);
user_pref("datareporting.sessions.current.main", 44);
user_pref("datareporting.sessions.current.sessionRestored", 723);
user_pref("datareporting.sessions.current.startTime", "1376674505069");
user_pref("datareporting.sessions.current.totalTime", 26);
user_pref("datareporting.sessions.currentIndex", 8);
user_pref("datareporting.sessions.previous.7", "{\"s\":1376615553982,\"a\":301,\"t\":57019,\"c\":true,\"m\":659,\"fp\":1986,\"sr\":2112}");
user_pref("datareporting.sessions.prunedIndex", 6);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:23.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1375816752000,\"rdfTime\":1375816728000}}}]");
user_pref("extensions.lastAppVersion", "23.0");
user_pref("extensions.lastPlatformVersion", "23.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20130806211916");
user_pref("gecko.mstone", "23.0");
user_pref("idle.lastDailyNotification", 1376617269);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1376635651);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1376529248);
user_pref("toolkit.startup.last_success", 1376674505);
user_pref("toolkit.telemetry.previousBuildID", "20130806211916");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1379048196);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
